-- ============================================================
-- Minha Obra — estrutura do banco (Versão 1). Fonte: PRD-BACKEND.md.
-- Listas fechadas com o texto IDÊNTICO ao de src/lib/vocabulario.js.
-- ============================================================

-- ── Pessoas ──────────────────────────────────────────────────
create table public.profiles (
  id bigint generated by default as identity primary key,
  -- vazio só nas pessoas de exemplo (sem login); quem se cadastra sempre tem
  auth_uid uuid unique references auth.users (id) on delete cascade,
  nome text not null default '',
  email text not null unique,
  role text not null default 'Aguardando' check (role in ('Aguardando', 'Engenheiro', 'Coordenador', 'Mestre', 'Cliente', 'Técnico de Segurança', 'Auxiliar Administrativo')),
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

-- ── Configuração geral (uma linha) ───────────────────────────
create table public.config (
  id int primary key default 1 check (id = 1),
  nome_construtora text not null,
  logo_construtora text,
  created_at timestamptz not null default now()
);

-- ── Obra ─────────────────────────────────────────────────────
create table public.obras (
  id bigint generated by default as identity primary key,
  nome text not null,
  cidade text not null,
  uf text not null,
  cliente text not null,
  data_inicio date not null,
  data_fim_contrato date not null,
  dia_fechamento_folha smallint not null check (dia_fechamento_folha between 1 and 31),
  status text not null default 'Em andamento' check (status in ('Em andamento', 'Paralisada', 'Concluída')),
  ultimo_calculo_em timestamptz,
  foto_obra text,
  logo_cliente text,
  created_at timestamptz not null default now()
);

create table public.obra_usuarios (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  profile_id bigint not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (obra_id, profile_id)
);

create table public.etapas_entrega (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  nome text not null,
  ordem smallint not null,
  data_entrega_contratual date,
  created_at timestamptz not null default now(),
  unique (obra_id, nome)
);

-- ── Cronograma ───────────────────────────────────────────────
create table public.servicos (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  uid_project int not null,
  pai_id bigint references public.servicos (id),
  etapa_entrega_id bigint references public.etapas_entrega (id),
  codigo_eap text not null,
  nome text not null,
  nivel smallint not null,
  e_resumo boolean not null default false,
  local text,
  unidade text not null default '%' check (unidade in ('%', 'm', 'm²', 'm³', 'kg', 't', 'un')),
  quantidade_prevista numeric(14,3) not null default 100 check (quantidade_prevista > 0),
  custo_orcado numeric(14,2),
  unidade_alterada_em timestamptz,
  inicio_previsto date not null,
  fim_previsto date not null,
  duracao_dias int not null,
  inicio_base date,
  fim_base date,
  inicio_cedo date,
  fim_tarde date,
  folga_dias int,
  critico boolean not null default false,
  quantidade_executada numeric(14,3) not null default 0,
  inicio_real date,
  fim_real date,
  dias_atraso int not null default 0,
  cancelado boolean not null default false,
  created_at timestamptz not null default now(),
  unique (obra_id, uid_project)
);
create index on public.servicos (obra_id, codigo_eap);
create index on public.servicos (obra_id, etapa_entrega_id);

create table public.servico_dependencias (
  id bigint generated by default as identity primary key,
  servico_id bigint not null references public.servicos (id) on delete cascade,
  predecessora_id bigint not null references public.servicos (id) on delete cascade,
  tipo text not null check (tipo in ('TI', 'II', 'TT', 'IT')),
  defasagem_dias int not null default 0,
  created_at timestamptz not null default now(),
  unique (servico_id, predecessora_id),
  check (servico_id <> predecessora_id)
);

create table public.restricoes (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  servico_id bigint not null references public.servicos (id) on delete cascade,
  tipo text not null check (tipo in ('Material', 'Projeto', 'Equipe', 'Equipamento', 'Liberação de área', 'Segurança', 'Outro')),
  descricao text not null,
  responsavel text,
  data_limite date,
  status text not null default 'Pendente' check (status in ('Pendente', 'Removida')),
  removida_em date,
  created_at timestamptz not null default now(),
  check (status <> 'Removida' or removida_em is not null)
);

-- ── Equipe ───────────────────────────────────────────────────
create table public.funcionarios (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  nome text not null,
  funcao text not null check (funcao in ('Servente', 'Pedreiro', 'Carpinteiro', 'Armador', 'Encanador', 'Eletricista', 'Operador de máquina', 'Motorista', 'Encarregado', 'Apontador', 'Almoxarife', 'Técnico', 'Outro')),
  tipo_mao_obra text not null check (tipo_mao_obra in ('Direta', 'Indireta', 'Terceirizada')),
  empresa text,
  matricula text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  check (tipo_mao_obra <> 'Terceirizada' or empresa is not null)
);

-- ── Pacotes ──────────────────────────────────────────────────
create table public.pacotes (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  servico_id bigint not null references public.servicos (id),
  nome text not null,
  local text not null,
  quantidade_meta numeric(14,3) not null check (quantidade_meta > 0),
  quantidade_executada numeric(14,3) not null default 0,
  valor_premio numeric(14,2) not null,
  data_inicio date not null,
  data_fechamento date not null,
  status text not null default 'Planejado' check (status in ('Planejado', 'Liberado', 'Em execução', 'Concluído', 'Não concluído')),
  motivo_nao_conclusao text check (motivo_nao_conclusao in ('Chuva', 'Falta de material', 'Falta de equipe', 'Projeto', 'Equipamento', 'Frente não liberada', 'Outro')),
  fechado_em timestamptz,
  created_at timestamptz not null default now(),
  check (status <> 'Não concluído' or motivo_nao_conclusao is not null)
);

create table public.presencas (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  data date not null,
  funcionario_id bigint not null references public.funcionarios (id),
  situacao text not null check (situacao in ('Presente', 'Falta', 'Atestado', 'Afastado')),
  pacote_id bigint references public.pacotes (id),
  lancado_por bigint not null references public.profiles (id),
  created_at timestamptz not null default now(),
  unique (funcionario_id, data),
  check (situacao = 'Presente' or pacote_id is null)
);
create index on public.presencas (obra_id, data);

create table public.premios (
  id bigint generated by default as identity primary key,
  pacote_id bigint not null references public.pacotes (id) on delete cascade,
  funcionario_id bigint not null references public.funcionarios (id),
  dias smallint not null,
  valor numeric(14,2) not null,
  created_at timestamptz not null default now()
);

-- ── PCP ──────────────────────────────────────────────────────
create table public.pcp_atividades (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  semana_inicio date not null check (extract(isodow from semana_inicio) = 1),
  data_prevista date not null,
  servico_id bigint not null references public.servicos (id),
  pacote_id bigint references public.pacotes (id),
  local text not null,
  quantidade_planejada numeric(14,3) not null check (quantidade_planejada > 0),
  equipe text,
  status text not null default 'Planejada' check (status in ('Planejada', 'Concluída', 'Não concluída')),
  quantidade_executada numeric(14,3),
  motivo_nao_conclusao text check (motivo_nao_conclusao in ('Chuva', 'Falta de material', 'Falta de equipe', 'Projeto', 'Equipamento', 'Frente não liberada', 'Outro')),
  baixa_por bigint references public.profiles (id),
  baixa_em timestamptz,
  copiada_de_id bigint references public.pcp_atividades (id),
  created_at timestamptz not null default now(),
  check (data_prevista between semana_inicio and semana_inicio + 5),
  check (status <> 'Não concluída' or motivo_nao_conclusao is not null)
);
create index on public.pcp_atividades (obra_id, semana_inicio);
create index on public.pcp_atividades (obra_id, data_prevista);

create table public.producoes (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  data date not null,
  servico_id bigint not null references public.servicos (id),
  quantidade numeric(14,3) not null,
  origem text not null check (origem in ('PCP', 'Ajuste')),
  pcp_atividade_id bigint unique references public.pcp_atividades (id) on delete cascade,
  pacote_id bigint references public.pacotes (id),
  motivo_ajuste text,
  lancado_por bigint not null references public.profiles (id),
  created_at timestamptz not null default now(),
  check (origem <> 'PCP' or pcp_atividade_id is not null),
  check (origem <> 'Ajuste' or motivo_ajuste is not null),
  check (origem = 'Ajuste' or quantidade >= 0)
);
create index on public.producoes (servico_id, data);

-- ── Ocorrências ──────────────────────────────────────────────
create table public.ocorrencias (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  numero int not null,
  titulo text not null,
  local text not null,
  etapa_entrega_id bigint references public.etapas_entrega (id),
  descricao text not null,
  status text not null default 'Aberta' check (status in ('Aberta', 'Em análise', 'Em tratamento', 'Resolvida', 'Recusada')),
  aberta_por bigint not null references public.profiles (id),
  aberta_em date not null default current_date,
  responsavel_id bigint references public.profiles (id),
  prazo date,
  resposta text,
  respondida_em timestamptz,
  fechada_em timestamptz,
  created_at timestamptz not null default now(),
  unique (obra_id, numero),
  check (status not in ('Resolvida', 'Recusada') or resposta is not null)
);

create table public.ocorrencia_fotos (
  id bigint generated by default as identity primary key,
  ocorrencia_id bigint not null references public.ocorrencias (id) on delete cascade,
  caminho text not null,
  enviada_por bigint not null references public.profiles (id),
  created_at timestamptz not null default now()
);

-- ── Gatilhos ─────────────────────────────────────────────────
-- Cadastro: toda conta nova vira um perfil "Aguardando".
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (auth_uid, nome, email, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'nome', ''), new.email, 'Aguardando');
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- Produção → quantidade executada, início e fim real do serviço, e do pacote ainda aberto.
create or replace function public.recalcular_executado()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  sid bigint := coalesce(new.servico_id, old.servico_id);
  pids bigint[] := array_remove(array[new.pacote_id, old.pacote_id], null);
begin
  update servicos s set
    quantidade_executada = coalesce(t.soma, 0),
    inicio_real = t.primeira,
    fim_real = case when coalesce(t.soma, 0) >= s.quantidade_prevista then coalesce(s.fim_real, t.ultima) end
  from (select sum(quantidade) soma, min(data) filter (where quantidade > 0) primeira, max(data) ultima
        from producoes where servico_id = sid) t
  where s.id = sid;
  update pacotes p set quantidade_executada = coalesce((select sum(quantidade) from producoes where pacote_id = p.id), 0)
  where p.id = any (pids) and p.fechado_em is null;
  return null;
end;
$$;
create trigger producoes_recalcular after insert or update or delete on public.producoes
  for each row execute function public.recalcular_executado();

-- Ocorrência: número sequencial por obra.
create or replace function public.numerar_ocorrencia()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.numero := coalesce((select max(numero) from ocorrencias where obra_id = new.obra_id), 0) + 1;
  return new;
end;
$$;
create trigger ocorrencias_numerar before insert on public.ocorrencias
  for each row execute function public.numerar_ocorrencia();
