-- Pacote com vários serviços, MO profissional/ajudante por serviço e colaboradores escolhidos
-- (pedido do Otoniel, 05/10/2026). Decisões:
--   * cada serviço do pacote tem a sua meta; o pacote só conclui quando TODOS batem a meta;
--   * MO profissional e MO ajudante em R$ por serviço; MO total = soma; prêmio do pacote = soma das MO totais;
--   * a parte profissional vai para os profissionais e a parte ajudante para os serventes (funcao = 'Servente'),
--     cada uma dividida pelos dias de presença no pacote;
--   * só os colaboradores escolhidos recebem, e o efetivo só lança o pacote para eles (terceirizado não entra).

-- 1. Tabelas novas.
create table public.pacote_servicos (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  pacote_id bigint not null references public.pacotes (id) on delete cascade,
  servico_id bigint not null references public.servicos (id),
  quantidade_meta numeric(14,3) not null check (quantidade_meta > 0),
  quantidade_executada numeric(14,3) not null default 0,
  mo_profissional numeric(14,2) not null default 0 check (mo_profissional >= 0),
  mo_ajudante numeric(14,2) not null default 0 check (mo_ajudante >= 0),
  mo_total numeric(14,2) generated always as (mo_profissional + mo_ajudante) stored,
  created_at timestamptz not null default now(),
  unique (pacote_id, servico_id)
);
create index pacote_servicos_servico_idx on public.pacote_servicos (servico_id);

create table public.pacote_colaboradores (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.obras (id) on delete cascade,
  pacote_id bigint not null references public.pacotes (id) on delete cascade,
  funcionario_id bigint not null references public.funcionarios (id),
  created_at timestamptz not null default now(),
  unique (pacote_id, funcionario_id)
);

-- 2. Os pacotes que já existem passam para o formato novo (o prêmio vira MO profissional; ninguém perde dado)
--    e quem já trabalhou num pacote vira colaborador dele.
insert into public.pacote_servicos (obra_id, pacote_id, servico_id, quantidade_meta, quantidade_executada, mo_profissional, mo_ajudante)
select obra_id, id, servico_id, quantidade_meta, quantidade_executada, valor_premio, 0 from public.pacotes;

insert into public.pacote_colaboradores (obra_id, pacote_id, funcionario_id)
select distinct pr.obra_id, pr.pacote_id, pr.funcionario_id
  from public.presencas pr join public.funcionarios f on f.id = pr.funcionario_id
 where pr.pacote_id is not null and f.tipo_mao_obra <> 'Terceirizada';

-- 3. Saem do pacote os campos que agora moram em pacote_servicos (antes, as regras que dependem deles).
drop policy pacotes_criar on public.pacotes;
drop policy pacotes_editar on public.pacotes;
drop function public.pacotes_sem_premio(bigint);
alter table public.pacotes drop column servico_id, drop column quantidade_meta, drop column quantidade_executada, drop column valor_premio;

-- 4. Regras de acesso.
--    Pacote: à mão só Planejado / Liberado / Em execução; Concluído, Não concluído e fechado_em saem do fechamento.
create policy pacotes_criar on public.pacotes for insert
  with check (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador']))
    and status in ('Planejado', 'Liberado', 'Em execução') and fechado_em is null);
create policy pacotes_editar on public.pacotes for update
  using (obra_id in (select minhas_obras()) and fechado_em is null and (select papel_em(array['Engenheiro', 'Coordenador'])))
  with check (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador']))
    and status in ('Planejado', 'Liberado', 'Em execução') and fechado_em is null);

--    Serviços do pacote (têm dinheiro: só Engenheiro e Coordenador; o Mestre lê pela função sem MO).
alter table public.pacote_servicos enable row level security;
create policy pacote_servicos_ver on public.pacote_servicos for select
  using (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador'])));
create policy pacote_servicos_criar on public.pacote_servicos for insert
  with check (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador'])) and quantidade_executada = 0
    and exists (select 1 from pacotes p where p.id = pacote_id and p.obra_id = pacote_servicos.obra_id and p.fechado_em is null)
    and exists (select 1 from servicos s where s.id = servico_id and s.obra_id = pacote_servicos.obra_id and not s.e_resumo));
create policy pacote_servicos_editar on public.pacote_servicos for update
  using (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador']))
    and exists (select 1 from pacotes p where p.id = pacote_id and p.fechado_em is null));
create policy pacote_servicos_apagar on public.pacote_servicos for delete
  using (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador'])) and quantidade_executada = 0
    and exists (select 1 from pacotes p where p.id = pacote_id and p.fechado_em is null));
-- A quantidade executada é do gatilho: pelo navegador só se mudam meta e MO.
revoke update on public.pacote_servicos from anon, authenticated;
grant update (quantidade_meta, mo_profissional, mo_ajudante) on public.pacote_servicos to authenticated;

--    Colaboradores (sem dinheiro: o Mestre lê, para o efetivo).
alter table public.pacote_colaboradores enable row level security;
create policy pacote_colaboradores_ver on public.pacote_colaboradores for select
  using (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador', 'Mestre'])));
create policy pacote_colaboradores_criar on public.pacote_colaboradores for insert
  with check (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador']))
    and exists (select 1 from pacotes p where p.id = pacote_id and p.obra_id = pacote_colaboradores.obra_id and p.fechado_em is null)
    and exists (select 1 from funcionarios f where f.id = funcionario_id and f.obra_id = pacote_colaboradores.obra_id and f.tipo_mao_obra <> 'Terceirizada'));
create policy pacote_colaboradores_apagar on public.pacote_colaboradores for delete
  using (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador']))
    and exists (select 1 from pacotes p where p.id = pacote_id and p.fechado_em is null));

--    Efetivo: só se lança o pacote para quem é colaborador dele.
drop policy presencas_criar on public.presencas;
create policy presencas_criar on public.presencas for insert
  with check (obra_id in (select minhas_obras()) and lancado_por = (select meu_perfil())
    and exists (select 1 from funcionarios f where f.id = funcionario_id and f.obra_id = presencas.obra_id)
    and (pacote_id is null or exists (select 1 from pacote_colaboradores pc where pc.pacote_id = presencas.pacote_id and pc.funcionario_id = presencas.funcionario_id))
    and ((select papel_em(array['Engenheiro', 'Coordenador']))
      or ((select papel_em(array['Mestre'])) and data >= (select hoje_local()) - 1)));
drop policy presencas_editar on public.presencas;
create policy presencas_editar on public.presencas for update
  using (obra_id in (select minhas_obras()) and (
    (select papel_em(array['Engenheiro', 'Coordenador']))
    or ((select papel_em(array['Mestre'])) and data >= (select hoje_local()) - 1)))
  with check (obra_id in (select minhas_obras()) and lancado_por = (select meu_perfil())
    and exists (select 1 from funcionarios f where f.id = funcionario_id and f.obra_id = presencas.obra_id)
    and (pacote_id is null or exists (select 1 from pacote_colaboradores pc where pc.pacote_id = presencas.pacote_id and pc.funcionario_id = presencas.funcionario_id))
    and ((select papel_em(array['Engenheiro', 'Coordenador']))
      or ((select papel_em(array['Mestre'])) and data >= (select hoje_local()) - 1)));

--    Atividade do PCP com pacote: o serviço da atividade tem de estar no pacote.
drop policy pcp_criar on public.pcp_atividades;
create policy pcp_criar on public.pcp_atividades for insert
  with check (obra_id in (select minhas_obras()) and (select papel_em(array['Engenheiro', 'Coordenador']))
    and data_prevista >= (select hoje_local()) and status = 'Planejada'
    and exists (select 1 from servicos s where s.id = servico_id and s.obra_id = pcp_atividades.obra_id)
    and (pacote_id is null or exists (select 1 from pacote_servicos ps where ps.pacote_id = pcp_atividades.pacote_id
      and ps.servico_id = pcp_atividades.servico_id and ps.obra_id = pcp_atividades.obra_id)));
drop policy pcp_editar on public.pcp_atividades;
create policy pcp_editar on public.pcp_atividades for update
  using (obra_id in (select minhas_obras()) and status = 'Planejada' and (select papel_em(array['Engenheiro', 'Coordenador'])))
  with check (obra_id in (select minhas_obras()) and status = 'Planejada' and (select papel_em(array['Engenheiro', 'Coordenador']))
    and exists (select 1 from servicos s where s.id = servico_id and s.obra_id = pcp_atividades.obra_id)
    and (pacote_id is null or exists (select 1 from pacote_servicos ps where ps.pacote_id = pcp_atividades.pacote_id
      and ps.servico_id = pcp_atividades.servico_id and ps.obra_id = pcp_atividades.obra_id)));

-- 5. Leituras sem dinheiro para o Mestre.
create function public.pacotes_sem_premio(p_obra bigint)
returns table (id bigint, obra_id bigint, nome text, local text, data_inicio date, data_fechamento date, status text,
               motivo_nao_conclusao text, fechado_em timestamptz)
language sql stable security definer set search_path = public as $$
  select id, obra_id, nome, local, data_inicio, data_fechamento, status, motivo_nao_conclusao, fechado_em
    from pacotes
   where obra_id = p_obra and p_obra in (select minhas_obras())
     and (select papel_em(array['Engenheiro', 'Coordenador', 'Mestre']))
$$;
create function public.pacote_servicos_sem_mo(p_obra bigint)
returns table (id bigint, pacote_id bigint, servico_id bigint, quantidade_meta numeric, quantidade_executada numeric)
language sql stable security definer set search_path = public as $$
  select id, pacote_id, servico_id, quantidade_meta, quantidade_executada
    from pacote_servicos
   where obra_id = p_obra and p_obra in (select minhas_obras())
     and (select papel_em(array['Engenheiro', 'Coordenador', 'Mestre']))
$$;

-- 6. Salvar pacote com serviços e colaboradores numa transação (roda com os direitos de quem chama:
--    a RLS acima continua valendo). p_id null = novo. Devolve o id do pacote.
create function public.salvar_pacote(p_obra bigint, p_id bigint, p_pacote jsonb, p_servicos jsonb, p_colaboradores jsonb)
returns bigint language plpgsql security invoker set search_path = public as $$
declare
  pid bigint := p_id;
begin
  if not (p_obra in (select minhas_obras()) and papel_em(array['Engenheiro', 'Coordenador'])) then
    raise exception 'Seu perfil não salva pacote.';
  end if;
  if coalesce(jsonb_array_length(p_servicos), 0) = 0 then raise exception 'Inclua pelo menos um serviço no pacote.'; end if;
  if pid is null then
    insert into pacotes (obra_id, nome, local, data_inicio, data_fechamento, status)
    values (p_obra, p_pacote->>'nome', p_pacote->>'local', (p_pacote->>'data_inicio')::date, (p_pacote->>'data_fechamento')::date, p_pacote->>'status')
    returning id into pid;
  else
    update pacotes set nome = p_pacote->>'nome', local = p_pacote->>'local', data_inicio = (p_pacote->>'data_inicio')::date,
           data_fechamento = (p_pacote->>'data_fechamento')::date, status = p_pacote->>'status'
     where id = pid and obra_id = p_obra and fechado_em is null;
    if not found then raise exception 'Pacote fechado na folha não pode ser editado.'; end if;
  end if;

  if exists (select 1 from pacote_servicos where pacote_id = pid and quantidade_executada > 0
               and servico_id not in (select (x->>'servico_id')::bigint from jsonb_array_elements(p_servicos) x)) then
    raise exception 'Um serviço com produção lançada não pode sair do pacote.';
  end if;
  delete from pacote_servicos
   where pacote_id = pid and servico_id not in (select (x->>'servico_id')::bigint from jsonb_array_elements(p_servicos) x);
  insert into pacote_servicos as ps (obra_id, pacote_id, servico_id, quantidade_meta, mo_profissional, mo_ajudante)
  select p_obra, pid, s.servico_id, s.quantidade_meta, s.mo_profissional, s.mo_ajudante
    from jsonb_to_recordset(p_servicos) as s(servico_id bigint, quantidade_meta numeric, mo_profissional numeric, mo_ajudante numeric)
  on conflict (pacote_id, servico_id) do update
    set quantidade_meta = excluded.quantidade_meta, mo_profissional = excluded.mo_profissional, mo_ajudante = excluded.mo_ajudante;

  delete from pacote_colaboradores
   where pacote_id = pid and funcionario_id not in (select x::bigint from jsonb_array_elements_text(coalesce(p_colaboradores, '[]')) x);
  insert into pacote_colaboradores (obra_id, pacote_id, funcionario_id)
  select p_obra, pid, x::bigint from jsonb_array_elements_text(coalesce(p_colaboradores, '[]')) x
  on conflict (pacote_id, funcionario_id) do nothing;
  return pid;
end;
$$;

-- 7. Produção → executado de cada serviço do pacote aberto (antes era um número só por pacote).
create or replace function public.recalcular_executado()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  sid bigint := coalesce(new.servico_id, old.servico_id);
  pids bigint[] := array_remove(array[new.pacote_id, old.pacote_id], null);
begin
  update servicos s set
    quantidade_executada = coalesce(t.soma, 0),
    inicio_real = t.primeira,
    fim_real = case when coalesce(t.soma, 0) >= s.quantidade_prevista then coalesce(s.fim_real, t.ultima) end
  from (select sum(quantidade) soma, min(data) filter (where quantidade > 0) primeira, max(data) ultima
        from producoes where servico_id = sid) t
  where s.id = sid;
  update pacote_servicos ps set quantidade_executada = coalesce((select sum(pr.quantidade) from producoes pr
         where pr.pacote_id = ps.pacote_id and pr.servico_id = ps.servico_id), 0)
   where ps.pacote_id = any (pids)
     and exists (select 1 from pacotes p where p.id = ps.pacote_id and p.fechado_em is null);
  return null;
end;
$$;

-- 8. Trocar % por quantidade converte também as metas do serviço nos pacotes.
create or replace function public.trocar_unidade(p_servico bigint, p_unidade text, p_quantidade numeric)
returns void language plpgsql security definer set search_path = public as $$
declare
  s servicos;
  f numeric;
begin
  select * into s from servicos where id = p_servico;
  if s.id is null or s.obra_id not in (select minhas_obras()) or not papel_em(array['Engenheiro', 'Coordenador']) then
    raise exception 'Seu perfil não troca a unidade.';
  end if;
  if s.unidade <> '%' then raise exception 'Este serviço já está medido em quantidade.'; end if;
  if p_unidade is null or p_unidade = '%' or p_quantidade is null or p_quantidade <= 0 then
    raise exception 'Escolha a unidade e informe a quantidade prevista.';
  end if;
  f := p_quantidade / s.quantidade_prevista;
  update servicos set unidade = p_unidade, quantidade_prevista = p_quantidade, unidade_alterada_em = now(),
         quantidade_executada = quantidade_executada * f
   where id = s.id;
  update pcp_atividades set quantidade_planejada = quantidade_planejada * f, quantidade_executada = quantidade_executada * f
   where servico_id = s.id;
  -- Pacote fechado também converte; os prêmios (R$) não mudam.
  update pacote_servicos set quantidade_meta = quantidade_meta * f, quantidade_executada = quantidade_executada * f
   where servico_id = s.id;
  update producoes set quantidade = quantidade * f where servico_id = s.id;
end;
$$;

-- 9. Fechamento da folha. Mesma regra de src/lib/premio.js (premioDoPacote): bateu a meta de TODOS os
--    serviços → Concluído; a MO profissional (soma dos serviços) é dividida entre os colaboradores
--    profissionais e a MO ajudante entre os serventes, cada parte pelos dias de presença no pacote entre o
--    início e o fechamento; o centavo que sobra vai para quem tem mais dias (empate: menor id).
create or replace function public.fechar_pacotes(p_obra bigint, p_data date, p_motivos jsonb)
returns json language plpgsql security definer set search_path = public as $$
declare
  p pacotes;
  r record;
  m text;
  parte text;
  valor numeric;
  tot_dias int;
  tot_cent bigint;
  distribuido bigint;
  fechados int := 0;
  total numeric := 0;
begin
  if not (p_obra in (select minhas_obras()) and papel_em(array['Engenheiro', 'Coordenador'])) then
    raise exception 'Seu perfil não fecha pacotes.';
  end if;
  for p in select * from pacotes where obra_id = p_obra and fechado_em is null and data_fechamento <= p_data order by id for update loop
    if not exists (select 1 from pacote_servicos where pacote_id = p.id) then
      raise exception 'Pacote % não tem nenhum serviço.', p.nome;
    end if;
    if not exists (select 1 from pacote_servicos where pacote_id = p.id and quantidade_executada < quantidade_meta) then
      foreach parte in array array['profissional', 'ajudante'] loop
        select coalesce(sum(case when parte = 'ajudante' then mo_ajudante else mo_profissional end), 0) into valor
          from pacote_servicos where pacote_id = p.id;
        continue when valor = 0;
        select count(*) into tot_dias
          from presencas pr
          join funcionarios f on f.id = pr.funcionario_id
          join pacote_colaboradores pc on pc.pacote_id = p.id and pc.funcionario_id = pr.funcionario_id
         where pr.pacote_id = p.id and pr.situacao = 'Presente' and pr.data between p.data_inicio and p.data_fechamento
           and f.tipo_mao_obra <> 'Terceirizada' and ((f.funcao = 'Servente') = (parte = 'ajudante'));
        if tot_dias = 0 then
          raise exception 'Pacote %: a MO % não tem nenhum colaborador % com presença registrada.', p.nome, parte,
            case when parte = 'ajudante' then 'servente' else 'profissional' end;
        end if;
        tot_cent := round(valor * 100)::bigint;
        distribuido := 0;
        for r in
          select pr.funcionario_id, count(*)::int dias
            from presencas pr
            join funcionarios f on f.id = pr.funcionario_id
            join pacote_colaboradores pc on pc.pacote_id = p.id and pc.funcionario_id = pr.funcionario_id
           where pr.pacote_id = p.id and pr.situacao = 'Presente' and pr.data between p.data_inicio and p.data_fechamento
             and f.tipo_mao_obra <> 'Terceirizada' and ((f.funcao = 'Servente') = (parte = 'ajudante'))
           group by pr.funcionario_id
           order by count(*) desc, pr.funcionario_id
        loop
          insert into premios (pacote_id, funcionario_id, dias, valor)
          values (p.id, r.funcionario_id, r.dias, (tot_cent * r.dias / tot_dias) / 100.0);
          distribuido := distribuido + tot_cent * r.dias / tot_dias;
        end loop;
        update premios set valor = valor + (tot_cent - distribuido) / 100.0
         where id = (select pm.id from premios pm join funcionarios f on f.id = pm.funcionario_id
                      where pm.pacote_id = p.id and ((f.funcao = 'Servente') = (parte = 'ajudante'))
                      order by pm.dias desc, pm.funcionario_id limit 1);
        total := total + valor;
      end loop;
      update pacotes set status = 'Concluído', motivo_nao_conclusao = null, fechado_em = now() where id = p.id;
    else
      m := p_motivos ->> p.id::text;
      if m is null then raise exception 'Escolha o motivo de não concluir o pacote %.', p.nome; end if;
      update pacotes set status = 'Não concluído', motivo_nao_conclusao = m, fechado_em = now() where id = p.id;
    end if;
    fechados := fechados + 1;
  end loop;
  if fechados = 0 then raise exception 'Nenhum pacote para fechar até esta data.'; end if;
  return json_build_object('fechados', fechados, 'total', total);
end;
$$;

revoke execute on function public.pacotes_sem_premio(bigint), public.pacote_servicos_sem_mo(bigint),
  public.salvar_pacote(bigint, bigint, jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.pacotes_sem_premio(bigint), public.pacote_servicos_sem_mo(bigint),
  public.salvar_pacote(bigint, bigint, jsonb, jsonb, jsonb) to authenticated;
